language: java
jdk:
  - openjdk11

branches:
  only:
    - master


#Travis CI Sever Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew build"

before_install:
  - chmod +x gradlew

#CI 실행 완료시 메일
notifications:
  email:
    recipients:
      - tkdduq8260@gmail.com